version: '3.3'
services:
  chainlit:
    build: ./chainlit
    image: chatui
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
