version: '3.3'
name: my-chatui
services:
  chainlit:
    container_name: chatui
    build:
      context: .
      dockerfile: chainlit/Dockerfile
      args:
        - CURRENT_DIR=$PWD
    image: chatui
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
